name: test

on: [push]

jobs:
  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GLFW
      run: sudo apt-get install libglfw3-dev valgrind
    - name: Initialize submodule
      run: git submodule update --init --recursive
    - name: Build dependency
      working-directory: external/MLX42
      run: |
        cmake -B build
        cmake --build build -j4
    - name: Build and run C project
      run: |
        make
    - name: Valgrind memory leak check #1
      run: |
        valgrind --leak-check=full --show-leak-kinds=all ./cub3D data/maps/default.cub
    - name: Valgrind memory leak check #2
      run: |
        valgrind --leak-check=full --show-leak-kinds=all ./cub3D data/maps/empty.cub

  build-on-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install GLFW
      run: brew install glfw
    - name: Initialize submodule
      run: git submodule update --init --recursive
    - name: Build dependency
      working-directory: external/MLX42
      run: |
        cmake -B build
        cmake --build build -j4
    - name: Build and run C project
      run: |
        make
