name: MacOS test

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install GLFW
      run: brew install glfw
    - name: Update xcode
      run: |
	   rm -rf /Library/Developer/CommandLineTools
       xcode-select --install
    - name: Initialize submodule
      run: git submodule update --init --recursive
    - name: Build dependency
      working-directory: external/MLX42
      run: |
        cmake -B build
        cmake --build build -j4
    - name: Build and run C project
      run: |
        make
